artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: https://github.com/Ashish14111995/Dataset_Chicken/blob/main/Chicken_fecal_Dataset.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion
